<?php

namespace UsersBundle\Repository;

/**
 * blackListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blackListRepository extends \Doctrine\ORM\EntityRepository
{
}
