<?php

namespace UsersBundle\Repository;

/**
 * friendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class friendsRepository extends \Doctrine\ORM\EntityRepository
{
}
