<?php

namespace UsersBundle\Repository;

/**
 * UsersHobbiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersHobbiesRepository extends \Doctrine\ORM\EntityRepository
{
}
